name: moneys
description: Manage money, currencies, budgets and other related things with ease.
version: 3.0.0
repository: https://github.com/Marco87Developer/moneys
homepage: https://marco87.dev

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  geos: ^1.3.2
  google_maps_flutter: ^2.0.6
  helpers_plethora: ^2.0.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
