name: moneys
description: Manage money, currencies, budgets and other related things with ease.
version: 3.0.0
documentation: https://docs.page/Marco87Developer/moneys
repository: https://github.com/Marco87Developer/moneys

environment:
  sdk: ">=2.14.4 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  geos: ^1.3.2
  google_maps_flutter: ^2.1.0
  helpers_plethora: ^2.0.6
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter: null
