name: moneys
<<<<<<< HEAD
description: Manage money, currencies, budgets and other related things with ease.
version: 3.0.0
=======
description: A set of classes useful for managing money, for save in a database and retrieve from it.
version: 2.1.1
>>>>>>> parent of 1632ea4 (Added Product class)
repository: https://github.com/Marco87Developer/moneys
homepage: https://marco87.dev

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  geos: ^1.3.2
=======

  geos: ^1.2.0
>>>>>>> parent of 1632ea4 (Added Product class)
  google_maps_flutter: ^2.0.6
  helpers_plethora: ^2.0.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
