name: moneys
description: A set of classes useful for managing money, for save in a database and retrieve from it.
version: 1.0.0
repository: https://github.com/Marco87Developer/moneys
homepage: https://marco87.dev

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  # flutter: ">=1.26.0-17.5.pre"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  pedantic: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
