name: moneys
description: Manage money, currencies, budgets and other related things with ease.
version: 3.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter: null
